2024-10-28 20:30:43.983 | INFO     | aiogram.dispatcher.dispatcher:start_polling:358 - Start polling.
2024-10-28 20:30:48.377 | INFO     | aiogram.contrib.middlewares.logging:on_pre_process_message:36 - Received message [ID:81] in chat [private:6948741611]
2024-10-28 20:30:48.688 | INFO     | aiogram.contrib.middlewares.logging:on_pre_process_error:150 - Process update [ID:728620806]: [failed] (in 311 ms)
2024-10-28 20:30:48.689 | ERROR    | asyncio.base_events:default_exception_handler:1785 - Task exception was never retrieved
future: <Task finished name='Task-375' coro=<Dispatcher._process_polling_updates() done, defined at C:\Users\newsp\OneDrive\Рабочий стол\shopbot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=WrongFileIdentifier('Wrong file identifier/http url specified')>
Traceback (most recent call last):

> File "C:\Users\newsp\OneDrive\Рабочий стол\shopbot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                     │         │     │                   │    │               │        └ True
                     │         │     │                   │    │               └ [<Update {"update_id": 728620806, "message": {"message_id": 81, "from": {"id": 6948741611, "is_bot": false, "first_name": "ve...
                     │         │     │                   │    └ <function Dispatcher.process_updates at 0x00000242F7CC62A0>
                     │         │     │                   └ <aiogram.dispatcher.dispatcher.Dispatcher object at 0x00000242F8172190>
                     │         │     └ <method 'from_iterable' of 'itertools.chain' objects>
                     │         └ <class 'itertools.chain'>
                     └ <module 'itertools' (built-in)>
  File "C:\Users\newsp\OneDrive\Рабочий стол\shopbot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
                 │       │       └ [<coroutine object Handler.notify at 0x00000242F7FFBD80>]
                 │       └ <function gather at 0x00000242F63A67A0>
                 └ <module 'asyncio' from 'C:\\Users\\newsp\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\__init__.py'>
  File "C:\Users\newsp\OneDrive\Рабочий стол\shopbot\venv\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     │           │        │       └ {}
                     │           │        └ (<Update {"update_id": 728620806, "message": {"message_id": 81, "from": {"id": 6948741611, "is_bot": false, "first_name": "ve...
                     │           └ <bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x00000242F8172190>>
                     └ Handler.HandlerObj(handler=<bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0...
  File "C:\Users\newsp\OneDrive\Рабочий стол\shopbot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
                 │    │                │      │      └ <aiogram.types.fields.Field object at 0x00000242F7B53DD0>
                 │    │                │      └ <Update {"update_id": 728620806, "message": {"message_id": 81, "from": {"id": 6948741611, "is_bot": false, "first_name": "ven...
                 │    │                └ <function Handler.notify at 0x00000242F7BF4C20>
                 │    └ <aiogram.dispatcher.handler.Handler object at 0x00000242F8172250>
                 └ <aiogram.dispatcher.dispatcher.Dispatcher object at 0x00000242F8172190>
  File "C:\Users\newsp\OneDrive\Рабочий стол\shopbot\venv\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     │           │        │       └ {'state': <aiogram.dispatcher.storage.FSMContext object at 0x00000242F8588250>}
                     │           │        └ (<Message {"message_id": 81, "from": {"id": 6948741611, "is_bot": false, "first_name": "venv∆", "username": "venvfuck", "lang...
                     │           └ <function start_message at 0x00000242F808C680>
                     └ Handler.HandlerObj(handler=<function start_message at 0x00000242F808C680>, spec=FullArgSpec(args=['message', 'state'], vararg...

  File "C:\Users\newsp\OneDrive\Рабочий стол\shopbot\handlers\common.py", line 179, in start_message
    msg = await message.answer_photo(pic, reply_markup=keyboard)
                │       │            │                 └ <ReplyKeyboardMarkup {"keyboard": [[{"text": "🏠 Города"}, {"text": "🆘 Поддержка"}], [{"text": "👤 Вакансии"}, {"text": "🛒 Пред...
                │       │            └ 'AgACAgIAAx0EZJqH4AADjmHEVLxueX7G6L9z7Q-zwqms97JoAAKrtjEbZ7whStBDD7Oh184UAQADAgADeQADIwQ'
                │       └ <function Message.answer_photo at 0x00000242F7B18220>
                └ <Message {"message_id": 81, "from": {"id": 6948741611, "is_bot": false, "first_name": "venv∆", "username": "venvfuck", "langu...

  File "C:\Users\newsp\OneDrive\Рабочий стол\shopbot\venv\Lib\site-packages\aiogram\types\message.py", line 511, in answer_photo
    return await self.bot.send_photo(
                 │    └ <property object at 0x00000242F716C220>
                 └ <Message {"message_id": 81, "from": {"id": 6948741611, "is_bot": false, "first_name": "venv∆", "username": "venvfuck", "langu...
  File "C:\Users\newsp\OneDrive\Рабочий стол\shopbot\venv\Lib\site-packages\aiogram\bot\bot.py", line 565, in send_photo
    result = await self.request(api.Methods.SEND_PHOTO, payload, files)
                   │    │       │   │       │           │        └ {}
                   │    │       │   │       │           └ {'chat_id': 6948741611, 'reply_markup': '{"keyboard": [[{"text": "🏠 Города"}, {"text": "🆘 Поддержка"}], [{"text": "👤 Вакансии...
                   │    │       │   │       └ <aiogram.utils.helper.Item object at 0x00000242F7B6A2D0>
                   │    │       │   └ <class 'aiogram.bot.api.Methods'>
                   │    │       └ <module 'aiogram.bot.api' from 'C:\\Users\\newsp\\OneDrive\\Рабочий стол\\shopbot\\venv\\Lib\\site-packages\\aiogram\\bot\\ap...
                   │    └ <function BaseBot.request at 0x00000242F7B8E480>
                   └ <aiogram.bot.bot.Bot object at 0x00000242F7D00350>
  File "C:\Users\newsp\OneDrive\Рабочий стол\shopbot\venv\Lib\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
                 │   │                  │    │              │    │       │             │       │     └ {}
                 │   │                  │    │              │    │       │             │       └ {'chat_id': 6948741611, 'reply_markup': '{"keyboard": [[{"text": "🏠 Города"}, {"text": "🆘 Поддержка"}], [{"text": "👤 Вакансии...
                 │   │                  │    │              │    │       │             └ 'sendPhoto'
                 │   │                  │    │              │    │       └ <aiogram.bot.bot.Bot object at 0x00000242F7D00350>
                 │   │                  │    │              │    └ TelegramAPIServer(base='https://api.telegram.org/bot{token}/{method}', file='https://api.telegram.org/file/bot{token}/{path}')
                 │   │                  │    │              └ <aiogram.bot.bot.Bot object at 0x00000242F7D00350>
                 │   │                  │    └ <function BaseBot.get_session at 0x00000242F7B8DC60>
                 │   │                  └ <aiogram.bot.bot.Bot object at 0x00000242F7D00350>
                 │   └ <function make_request at 0x00000242F7B55300>
                 └ <module 'aiogram.bot.api' from 'C:\\Users\\newsp\\OneDrive\\Рабочий стол\\shopbot\\venv\\Lib\\site-packages\\aiogram\\bot\\ap...
  File "C:\Users\newsp\OneDrive\Рабочий стол\shopbot\venv\Lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           │            │       │        │             │        │             │        └ <function ClientResponse.text at 0x00000242F6DE3060>
           │            │       │        │             │        │             └ <ClientResponse(https://api.telegram.org/bot7774045102:AAGxE103tpOlQKWOW3IVPbopmk6yCGzOJMI/sendPhoto) [400 Bad Request]>
           │            │       │        │             │        │               <CIM...
           │            │       │        │             │        └ 400
           │            │       │        │             └ <ClientResponse(https://api.telegram.org/bot7774045102:AAGxE103tpOlQKWOW3IVPbopmk6yCGzOJMI/sendPhoto) [400 Bad Request]>
           │            │       │        │               <CIM...
           │            │       │        └ <property object at 0x00000242F6CE8630>
           │            │       └ <ClientResponse(https://api.telegram.org/bot7774045102:AAGxE103tpOlQKWOW3IVPbopmk6yCGzOJMI/sendPhoto) [400 Bad Request]>
           │            │         <CIM...
           │            └ 'sendPhoto'
           └ <function check_result at 0x00000242F7B55440>
  File "C:\Users\newsp\OneDrive\Рабочий стол\shopbot\venv\Lib\site-packages\aiogram\bot\api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
    │          │          │      └ 'Bad Request: wrong file identifier/HTTP URL specified'
    │          │          └ <classmethod(<function _MatchErrorMixin.detect at 0x00000242F71494E0>)>
    │          └ <class 'aiogram.utils.exceptions.BadRequest'>
    └ <module 'aiogram.utils.exceptions' from 'C:\\Users\\newsp\\OneDrive\\Рабочий стол\\shopbot\\venv\\Lib\\site-packages\\aiogram...
  File "C:\Users\newsp\OneDrive\Рабочий стол\shopbot\venv\Lib\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
          │   │   │       └ 'bad request: wrong file identifier/http url specified'
          │   │   └ None
          │   └ <class 'aiogram.utils.exceptions.BadRequest'>
          └ <class 'aiogram.utils.exceptions.WrongFileIdentifier'>

aiogram.utils.exceptions.WrongFileIdentifier: Wrong file identifier/http url specified
2024-10-28 20:35:57.423 | INFO     | tortoise:close_connections:552 - Tortoise-ORM shutdown
2024-10-28 20:35:57.423 | INFO     | aiogram.dispatcher.dispatcher:stop_polling:433 - Stop polling...
2024-10-28 20:35:57.423 | WARNING  | aiogram.utils.executor:start_polling:329 - Goodbye!
